name 'TopHat'
maintainer 'The Authors'
maintainer_email 'chef@eaglegenomics.com'
license 'all_rights'
description 'Installs/Configures TopHat'
long_description 'Installs/Configures TopHat'
version '1.0.0'

depends 'build-essential'
depends 'boost-source'
depends 'magic_shell'
depends 'Bowtie'
